{% set name = "lauetoolsnn" %}
{% set version = "3.0.62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lauetoolsnn-{{ version }}.tar.gz
  sha256: 02085b597f2a1f4e8dbb859ad334b40b6f882009de10583808c26e8431a1828f

build:
  entry_points:
    - lauetoolsnn=lauetoolsnn.lauetoolsneuralnetwork:start
    - lauenn=lauetoolsnn.lauetoolsneuralnetwork:start
    - lauenn_addmat=lauetoolsnn.util_scripts.add_material:start
    - lauenn_mat=lauetoolsnn.util_scripts.add_material:querymat
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  osx_is_app: True
  
requirements:
  host:
    - python >=3.6
    - tqdm
    - scikit-image
    - fabio
    - scikit-learn
    - tensorflow
    - h5py
    - keras
    - networkx
    - pyqt
    - matplotlib-base
    - scipy
    - numpy
    - pip
  run:
    - python >=3.6
    - tqdm
    - scikit-image
    - fabio
    - scikit-learn
    - tensorflow
    - h5py
    - keras
    - networkx
    - pyqt
    - matplotlib-base
    - scipy
    - numpy

test:
  imports:
    - lauetoolsnn
    - keras
    - scipy
    - numpy
    - h5py
    - tensorflow
    - PyQt5
    - sklearn
    - skimage
    - fabio
    - networkx
    - tqdm
    
about:
  home: https://github.com/ravipurohit1991/lauetoolsnn
  summary: LaueNN- neural network training and prediction routine to index single and polycrystalline Laue diffraction patterns
  license: MIT

app:
  entry: lauetoolsnn
  icon: icon.png
  summary:  "Neural network workflow for indexation of Laue patterns"
  type: desk
  
extra:
  recipe-maintainers:
    - ravipurohit1991
