{% set name = "lauetoolsnn" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  entry_points:
    {% for entry_point in data['entry_points']['console_scripts'] %}
    - {{ entry_point }}
    {% endfor %}
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  build:
    - python
    - pip
    - setuptools
  host:
    - python
    - matplotlib-base
    - keras
    - scipy
    - numpy
    - h5py
    - tensorflow
    - pyqt
    - scikit-learn
    - fabio
    - networkx
    - scikit-image
    - tqdm
    - pip
  run:
    - python >=3.6
    - matplotlib-base >=3.4.2
    - keras >=2.7.0
    - scipy >=1.7.0
    - numpy >=1.18.5
    - h5py >=3.1
    - tensorflow >=2.7.0
    - pyqt >=5.9
    - scikit-learn >=0.24.2
    - fabio >=0.11.0
    - networkx >=2.6.3
    - scikit-image >=0.18.0
    - tqdm >=4.60.0

test:
  imports:
    - lauetoolsnn
    - keras
    - scipy
    - numpy
    - h5py
    - tensorflow
    - PyQt5
    - sklearn
    - skimage
    - fabio
    - networkx
    - tqdm
    
about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}

app:
  entry: lauetoolsnn
  icon: icon.png
  summary:  "Neural network workflow for indexation of Laue patterns"
  type: desk
  
extra:
  recipe-maintainers:
    - ravipurohit
