{% set name = "lauetoolsnn" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  entry_points:
    - lauetoolsnn=lauetoolsnn.lauetoolsneuralnetwork:start
    - lauenn=lauetoolsnn.lauetoolsneuralnetwork:start
    - lauenn_addmat=lauetoolsnn.util_scripts.add_material:start
    - lauenn_mat=lauetoolsnn.util_scripts.add_material:querymat
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  osx_is_app: True

requirements:
  build:
    - python
    - setuptools
    - pip
  host:
    - python >=3.7
    - scikit-image
    - fabio
    - scikit-learn
    - tensorflow
    - h5py
    - keras
    - networkx
    - pyqt
    - matplotlib-base
    - scipy
    - numpy
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - keras
    - scipy
    - numpy
    - h5py
    - tensorflow
    - pyqt
    - scikit-learn
    - fabio
    - networkx
    - scikit-image

test:
  imports:
    - lauetoolsnn
    - keras
    - scipy
    - numpy
    - h5py
    - tensorflow
    - PyQt5
    - sklearn
    - skimage
    - fabio
    - networkx
    
about:
  home: https://github.com/ravipurohit1991/lauetoolsnn
  summary: LaueNN- neural network training and prediction routine to index single and polycrystalline Laue diffraction patterns
  license: MIT
  
extra:
  recipe-maintainers:
    - ravipurohit1991
