name: Publish

on: [release]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: publish-to-conda
      uses: ravipurohit1991/publish_conda_package_action@2.0.3
      with:
        # CondaDir: locate the directory containing your meta.yml, conda_build_config.yaml (...) files
        CondaDir: 'conda.recipe'
        # Channels: You can add more channel with a space separator
        Channels: 'conda-forge' 
        # Platforms: remove one or more of these platforms
        Platforms: 'noarch'
        CondaUsername: ${{ secrets.CONDA_USERNAME }}
        CondaPassword: ${{ secrets.CONDA_PASSWORD }}
